### PR TITLE
Gloomrot Update

### PR DESCRIPTION
**Pull request by p1xel8ted**
Gloomrot Update

### CODE REVIEW

**Comment by PweSol** [comment]
I have been unsuccessful in compiling your update. Are you sure it works correctly?

**Comment by p1xel8ted** [comment]
It does.

**Comment by PweSol** [comment]
Could you compile it pretty please? PureDark doesn't seem to be releasing it either.

**Comment by Eraistein** [comment]
Heya p1xel. I've tried everything I can to compile your build, but was also unsucessful. Could you compile it for us when you get the time, please? q

**Pull request merged**
